server:
  port: 5187
  servlet: 
   context-path: /iot-service
  uri-encoding: utf-8

###加密密钥
jasypt:
  encryptor:
    password: ecar

spring:
  datasource:
    eocdb:
      url: jdbc:mysql://10.66.119.193:3306/eoc?characterEncoding=utf8&useUnicode=true
      driver-class-name: com.mysql.jdbc.Driver
      username: eoc_app
      password: 'e@lecardb*'
      connection-timeout: 30000
      minimum-idle: 20
      maximum-pool-size: 20
    simdb:
      url: jdbc:mysql://10.66.122.93:3306/sim_eoc?characterEncoding=utf8&useUnicode=true
      driver-class-name: com.mysql.jdbc.Driver
      username: eoc_read
      password: 'eoc@read#ecar'
      connection-timeout: 30000
      minimum-idle: 20
      maximum-pool-size: 20
    iotdb:
      url: jdbc:mysql://10.66.119.193:3306/iot?characterEncoding=utf8&useUnicode=true
      username: iot_user
      password: ENC(bCppqzXXCwLPQss569e7+o94UTsgmVMTOf+FUvYaGFE=)
      hikari:
        driver-class-name: com.mysql.jdbc.Driver
        connection-timeout: 30000
        minimum-idle: 20
        maximum-pool-size: 20
      
      
  redis:
    host: 10.66.187.163
    database: 0
    port: 6379
    password: 'ecar#201808'
    timeout: 2000
    lettuce:
      pool:
        max-active: 1024
        max-wait: 256
        max-idle: 512
        min-idle: 256
        
  data:
    mongodb:
      uri: 'mongodb://rwuser:qiuyu#9964@10.66.141.81:27017/admin?authMechanism=MONGODB-CR'
      database: eoc 

#自定义参数配置
ecar:
 iot:
   IS_PRODUCT_ENVIRONMENT: true
   tripReport_default_notice_mileage: 20
  